baseURL = "http://172.17.0.3:32768/"
languageCode = "en-us"
title = "RUN ARMY"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-107562055-1"
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "The Maknae Line"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2018-02-18"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "yeongtan.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**Arf I'm Yeontan**<br> Join me and the rest of PH ARMYs<br> as we celebrate <br> BTS' 5th anniversary"
		# [HTML5 UP](//html5up.net).
		# The icons will be shown if you enter your username
		twitter = "jiminqkr"
		#github = "spf13"
		#gitlab = "spf13"
		#dribbble = ""
		facebook = "TheMaknaeLine"
		#googleplus = ""
		#flickr = ""
		#linkedin = ""

		#copyright = [
		#	"&copy; John Doe",
		#	"Design: [HTML5 UP](//html5up.net)",
		#	"Demo Images: [Unsplash](//unsplash.com/)"
		#]


	[params.about]
		hide  = false
		title = "RUN ARMY Episode 1: Manila"
		content = "The first fun for a cause for ARMYs in the Metro. <br> Proceeds of the the RUN ARMY will be donated to #EndViolence Campaign of UNICEF"


	[params.portfolio]
		hide  = false
		title = "Presented By"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "header.jpeg"
			thumb = "header.jpeg"
			title = "[Be The Star BTS](//twitter.com/BeTheStarBTS)"
			description = "Stan all Bangtan Sonyeondan (@BTS_twt) / UNICEF Advocate"

	[params.partners]
		hide  = false
		title = "In Cooperation With"

	[[params.partners.gallery]]
		image = "kingnamjoonph.jpg"
		thumb = "kingnamjoonph.jpg"
		title = "[KingNamjoonPH](//twitter.com/KingNamjoonPH)"
		description = "Independent fan base for BTS’ RM • #PHFlagOcean • #OneLoveNamjoonProject"

	[[params.partners.gallery]]
		image = "btsphtrends.jpg"
		thumb = "btsphtrends.jpg"
		title = "[BTS PH Trendsetter](//twitter.com/btsphtrends)"
		description = "Official Trendsetter team of @BTS_twt in the Philippines. BTS PH Trendsetter "

	[[params.partners.gallery]]
		image = "global-bts.jpg"
		thumb = "global-bts.jpg"
		title = "[Global BTS](//www.facebook.com/GlobalBTSnet)"
		description = "Global BTS on Facebook"

	[[params.partners.gallery]]
		image = "btsmaknaeline.jpg"
		thumb = "btsmaknaeline.jpg"
		title = "[The Maknae Line](//www.facebook.com/TheMaknaeLine)"
		description = "BTS Maknae Line on Facebook"



	[params.recentposts]
		hide  = false
		title = "Check This Out"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Follow BTS on Twitter, Facebook, Youtube. <br> "

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "14.5676293,120.7404389,10z"
		address = [
			"Metro Manila, ",
			"Philippines"
		]
		phone = "+63 977 626 1764"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "wowowoojijung@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
weight = 0